/**
 *
 * $Id$
 */
package aSA.validation;

import aSA.Configuration;
import aSA.Contrainte;
import aSA.Interface;
import aSA.Propriete;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link aSA.Composant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComposantValidator {
	boolean validate();

	boolean validateSystem_pere(Configuration value);

	boolean validateSystem_fils(EList<Configuration> value);

	boolean validateInterface(EList<Interface> value);

	boolean validateContrainte(Contrainte value);

	boolean validatePropriete(Propriete value);
}
