/**
 *
 * $Id$
 */
package aSA.validation;

import aSA.Attachement;
import aSA.Binding;
import aSA.Composant;
import aSA.Connecteur;
import aSA.Interface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link aSA.Configuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurationValidator {
	boolean validate();

	boolean validateComposant(EList<Composant> value);

	boolean validateConnecteur(EList<Connecteur> value);

	boolean validateAttachements(EList<Attachement> value);

	boolean validateInterface(Interface value);

	boolean validateBinding(EList<Binding> value);
}
