/**
 *
 * $Id$
 */
package aSA.validation;

import aSA.Configuration;
import aSA.Glue;
import aSA.Interface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link aSA.Connecteur}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnecteurValidator {
	boolean validate();

	boolean validateSystem(Configuration value);

	boolean validateInterface(EList<Interface> value);

	boolean validateGlue(EList<Glue> value);
}
